In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
### 週販レポート2025年版

# 標準ライブラリ
from datetime import datetime, timedelta

# サードパーティライブラリ
import polars as pl
import matplotlib.pyplot as plt
import japanize_matplotlib
from matplotlib.ticker import ScalarFormatter
from IPython.display import Markdown, display

import gamedata as g

pl.Config.set_tbl_rows(40)
pl.Config.set_tbl_cols(-1)

polars.config.Config

## load_hard_sales

In [3]:
base_df = g.load_hard_sales()
base_df.schema

Schema([('weekly_id', String),
        ('begin_date', Date),
        ('end_date', Date),
        ('report_date', Date),
        ('period_date', Int16),
        ('hw', String),
        ('units', Int64),
        ('adjust_units', Int64),
        ('year', Int16),
        ('month', Int16),
        ('mday', Int16),
        ('week', Int16),
        ('delta_day', Int32),
        ('delta_week', Int32),
        ('delta_month', Int16),
        ('delta_year', Int16),
        ('avg_units', Int64),
        ('sum_units', Int64),
        ('launch_date', Date),
        ('maker_name', String),
        ('full_name', String),
        ('quarter', String)])

In [4]:
base_df

┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ wee ┆ beg ┆ end ┆ rep ┆ per ┆ hw  ┆ uni ┆ adj ┆ yea ┆ mon ┆ mda ┆ wee ┆ del ┆ del ┆ del ┆ del ┆ avg ┆ sum ┆ lau ┆ mak ┆ ful ┆ qua │
│ kly ┆ in_ ┆ _da ┆ ort ┆ iod ┆ --- ┆ ts  ┆ ust ┆ r   ┆ th  ┆ y   ┆ k   ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ _un ┆ _un ┆ nch ┆ er_ ┆ l_n ┆ rte │
│ _id ┆ dat ┆ te  ┆ _da ┆ _da ┆ str ┆ --- ┆ _un ┆ --- ┆ --- ┆ --- ┆ --- ┆ day ┆ wee ┆ mon ┆ yea ┆ its ┆ its ┆ _da ┆ nam ┆ ame ┆ r   │
│ --- ┆ e   ┆ --- ┆ te  ┆ te  ┆     ┆ i64 ┆ its ┆ i16 ┆ i16 ┆ i16 ┆ i16 ┆ --- ┆ k   ┆ th  ┆ r   ┆ --- ┆ --- ┆ te  ┆ e   ┆ --- ┆ --- │
│ str ┆ --- ┆ dat ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ str ┆ str │
│     ┆ dat ┆ e   ┆ dat ┆ i16 ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ i16 ┆ i16 ┆     ┆     ┆ dat ┆ str ┆     ┆     │
│     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ GB  ┆ 10, ┆ 0   ┆ 1,9 ┆ 10  ┆ 18  ┆ 3   ┆ 3,4 ┆ 495 ┆ 114 ┆ 9   ┆ 1,5 ┆ 10, ┆ 198 ┆ Nin ┆ GAM ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 867 ┆     ┆ 98  ┆     ┆     ┆     ┆ 67  ┆     ┆     ┆     ┆ 52  ┆ 867 ┆ 9-0 ┆ ten ┆ E   ┆ 8Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4-2 ┆ do  ┆ BOY ┆     │
│ 8_G ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ N64 ┆ 2,9 ┆ 0   ┆ 1,9 ┆ 10  ┆ 18  ┆ 3   ┆ 847 ┆ 121 ┆ 28  ┆ 2   ┆ 423 ┆ 2,9 ┆ 199 ┆ Nin ┆ NIN ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 65  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 65  ┆ 6-0 ┆ ten ┆ TEN ┆ 8Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-2 ┆ do  ┆ DO6 ┆     │
│ 8_N ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     │
│ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ PS  ┆ 20, ┆ 0   ┆ 1,9 ┆ 10  ┆ 18  ┆ 3   ┆ 1,4 ┆ 202 ┆ 46  ┆ 4   ┆ 2,9 ┆ 20, ┆ 199 ┆ SON ┆ Pla ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 918 ┆     ┆ 98  ┆     ┆     ┆     ┆ 15  ┆     ┆     ┆     ┆ 88  ┆ 918 ┆ 4-1 ┆ Y   ┆ ySt ┆ 8Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆ ati ┆     │
│ 8_P ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ on  ┆     │
│ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ SAT ┆ 858 ┆ 0   ┆ 1,9 ┆ 10  ┆ 18  ┆ 3   ┆ 1,4 ┆ 203 ┆ 47  ┆ 4   ┆ 122 ┆ 858 ┆ 199 ┆ SEG ┆ SEG ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ URN ┆     ┆     ┆ 98  ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆ 4-1 ┆ A   ┆ A   ┆ 8Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-2 ┆     ┆ SAT ┆     │
│ 8_S ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ URN ┆     │
│ ATU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ RN  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ GB  ┆ 163 ┆ 0   ┆ 1,9 ┆ 10  ┆ 25  ┆ 4   ┆ 3,4 ┆ 496 ┆ 114 ┆ 9   ┆ 23, ┆ 173 ┆ 198 ┆ Nin ┆ GAM ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ ,01 ┆     ┆ 98  ┆     ┆     ┆     ┆ 74  ┆     ┆     ┆     ┆ 288 ┆ ,88 ┆ 9-0 ┆ ten ┆ E   ┆ 8Q4 │
│ 0-2 ┆ 0-1 ┆ 0-2 ┆ 0-2 ┆     ┆     ┆ 7   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 4-2 ┆ do  ┆ BOY ┆     │
│ 5_G ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ N64 ┆ 3,8 ┆ 0   ┆ 1,9 ┆ 10  ┆ 25  ┆ 4   ┆ 854 ┆ 122 ┆ 28  ┆ 2   ┆ 544 ┆ 6,7 ┆ 199 ┆ Nin ┆ NIN ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 13  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 78  ┆ 6-0 ┆ ten ┆ TEN ┆ 8Q4 │
│ 0-2 ┆ 0-1 ┆ 0-2 ┆ 0-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-2 ┆ do  ┆ DO6 ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     │
│ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ PS  ┆ 21, ┆ 0   ┆ 1,9 ┆ 10  ┆ 25  ┆ 4   ┆ 1,4 ┆ 203 ┆ 46  ┆ 4   ┆ 3,0 ┆ 42, ┆ 199 ┆ SON ┆ Pla ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 151 ┆     ┆ 98  ┆     ┆     ┆     ┆ 22  ┆     ┆     ┆     ┆ 21  ┆ 069 ┆ 4-1 ┆ Y   ┆ ySt ┆ 8Q4 │
│ 0-2 ┆ 0-1 ┆ 0-2 ┆ 0-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆ ati ┆     │
│ 5_P ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ on  ┆     │
│ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ SAT ┆ 1,0 ┆ 0   ┆ 1,9 ┆ 10  ┆ 25  ┆ 4   ┆ 1,4 ┆ 204 ┆ 47  ┆ 4   ┆ 151 ┆ 1,9 ┆ 199 ┆ SEG ┆ SEG ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ URN ┆ 61  ┆     ┆ 98  ┆     ┆     ┆     ┆ 33  ┆     ┆     ┆     ┆     ┆ 19  ┆ 4-1 ┆ A   ┆ A   ┆ 8Q4 │
│ 0-2 ┆ 0-1 ┆ 0-2 ┆ 0-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-2 ┆     ┆ SAT ┆     │
│ 5_S ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ URN ┆     │
│ ATU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ RN  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ GB  ┆ 71, ┆ 0   ┆ 1,9 ┆ 11  ┆ 1   ┆ 1   ┆ 3,4 ┆ 497 ┆ 115 ┆ 9   ┆ 10, ┆ 245 ┆ 198 ┆ Nin ┆ GAM ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 679 ┆     ┆ 98  ┆     ┆     ┆     ┆ 81  ┆     ┆     ┆     ┆ 239 ┆ ,56 ┆ 9-0 ┆ ten ┆ E   ┆ 8Q4 │
│ 1-0 ┆ 0-2 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆ 4-2 ┆ do  ┆ BOY ┆     │
│ 1_G ┆ 6   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ N64 ┆ 3,7 ┆ 0   ┆ 1,9 ┆ 11  ┆ 1   ┆ 1   ┆ 861 ┆ 123 ┆ 29  ┆ 2   ┆ 541 ┆ 10, ┆ 199 ┆ Nin ┆ NIN ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 87  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 565 ┆ 6-0 ┆ ten ┆ TEN ┆ 8Q4 │
│ 1-0 ┆ 0-2 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-2 ┆ do  ┆ DO6 ┆     │
│ 1_N ┆ 6   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     │
│ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ Neo ┆ 21, ┆ 0   ┆ 1,9 ┆ 11  ┆ 1   ┆ 1   ┆ 4   ┆ 0   ┆ 1   ┆ 0   ┆ 3,0 ┆ 21, ┆ 199 ┆ SNK ┆ Neo ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ Geo ┆ 471 ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 67  ┆ 471 ┆ 8-1 ┆     ┆ Geo ┆ 8Q4 │
│ 1-0 ┆ 0-2 ┆ 1-0 ┆ 1-0 ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0-2 ┆     ┆ Poc ┆     │
│ 1_N ┆ 6   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ ket ┆     │
│ eoG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ eoP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ PS  ┆ 20, ┆ 0   ┆ 1,9 ┆ 11  ┆ 1   ┆ 1   ┆ 1,4 ┆ 204 ┆ 47  ┆ 4   ┆ 2,8 ┆ 62, ┆ 199 ┆ SON ┆ Pla ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 128 ┆     ┆ 98  ┆     ┆     ┆     ┆ 29  ┆     ┆     ┆     ┆ 75  ┆ 197 ┆ 4-1 ┆ Y   ┆ ySt ┆ 8Q4 │
│ 1-0 ┆ 0-2 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆ ati ┆     │
│ 1_P ┆ 6   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ on  ┆     │
│ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ SAT ┆ 1,0 ┆ 0   ┆ 1,9 ┆ 11  ┆ 1   ┆ 1   ┆ 1,4 ┆ 205 ┆ 48  ┆ 4   ┆ 146 ┆ 2,9 ┆ 199 ┆ SEG ┆ SEG ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ URN ┆ 27  ┆     ┆ 98  ┆     ┆     ┆     ┆ 40  ┆     ┆     ┆     ┆     ┆ 46  ┆ 4-1 ┆ A   ┆ A   ┆ 8Q4 │
│ 1-0 ┆ 0-2 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-2 ┆     ┆ SAT ┆     │
│ 1_S ┆ 6   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ URN ┆     │
│ ATU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ RN  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ GB  ┆ 52, ┆ 0   ┆ 1,9 ┆ 11  ┆ 8   ┆ 2   ┆ 3,4 ┆ 498 ┆ 115 ┆ 9   ┆ 7,5 ┆ 298 ┆ 198 ┆ Nin ┆ GAM ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 586 ┆     ┆ 98  ┆     ┆     ┆     ┆ 88  ┆     ┆     ┆     ┆ 12  ┆ ,14 ┆ 9-0 ┆ ten ┆ E   ┆ 8Q4 │
│ 1-0 ┆ 1-0 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 9   ┆ 4-2 ┆ do  ┆ BOY ┆     │
│ 8_G ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ N64 ┆ 4,9 ┆ 0   ┆ 1,9 ┆ 11  ┆ 8   ┆ 2   ┆ 868 ┆ 124 ┆ 29  ┆ 2   ┆ 708 ┆ 15, ┆ 199 ┆ Nin ┆ NIN ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 62  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 527 ┆ 6-0 ┆ ten ┆ TEN ┆ 8Q4 │
│ 1-0 ┆ 1-0 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-2 ┆ do  ┆ DO6 ┆     │
│ 8_N ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     │
│ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ Neo ┆ 4,6 ┆ 0   ┆ 1,9 ┆ 11  ┆ 8   ┆ 2   ┆ 11  ┆ 1   ┆ 1   ┆ 0   ┆ 669 ┆ 26, ┆ 199 ┆ SNK ┆ Neo ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ Geo ┆ 88  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 159 ┆ 8-1 ┆     ┆ Geo ┆ 8Q4 │
│ 1-0 ┆ 1-0 ┆ 1-0 ┆ 1-0 ┆     ┆ P   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0-2 ┆     ┆ Poc ┆     │
│ 8_N ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 8   ┆     ┆ ket ┆     │
│ eoG ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ eoP ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ PS  ┆ 27, ┆ 0   ┆ 1,9 ┆ 11  ┆ 8   ┆ 2   ┆ 1,4 ┆ 205 ┆ 47  ┆ 4   ┆ 3,8 ┆ 89, ┆ 199 ┆ SON ┆ Pla ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 171 ┆     ┆ 98  ┆     ┆     ┆     ┆ 36  ┆     ┆     ┆     ┆ 81  ┆ 368 ┆ 4-1 ┆ Y   ┆ ySt ┆ 8Q4 │
│ 1-0 ┆ 1-0 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2-0 ┆     ┆ ati ┆     │
│ 8_P ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ on  ┆     │
│ S   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ SAT ┆ 824 ┆ 0   ┆ 1,9 ┆ 11  ┆ 8   ┆ 2   ┆ 1,4 ┆ 206 ┆ 48  ┆ 4   ┆ 117 ┆ 3,7 ┆ 199 ┆ SEG ┆ SEG ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆ URN ┆     ┆     ┆ 98  ┆     ┆     ┆     ┆ 47  ┆     ┆     ┆     ┆     ┆ 70  ┆ 4-1 ┆ A   ┆ A   ┆ 8Q4 │
│ 1-0 ┆ 1-0 ┆ 1-0 ┆ 1-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1-2 ┆     ┆ SAT ┆     │
│ 8_S ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ URN ┆     │
│ ATU ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ RN  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ GB  ┆ 37, ┆ 0   ┆ 1,9 ┆ 11  ┆ 15  ┆ 3   ┆ 3,4 ┆ 499 ┆ 115 ┆ 9   ┆ 5,3 ┆ 335 ┆ 198 ┆ Nin ┆ GAM ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 727 ┆     ┆ 98  ┆     ┆     ┆     ┆ 95  ┆     ┆     ┆     ┆ 89  ┆ ,87 ┆ 9-0 ┆ ten ┆ E   ┆ 8Q4 │
│ 1-1 ┆ 1-0 ┆ 1-1 ┆ 1-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 4-2 ┆ do  ┆ BOY ┆     │
│ 5_G ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆     ┆     ┆     │
│ B   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 199 ┆ 199 ┆ 199 ┆ 199 ┆ 7   ┆ N64 ┆ 4,9 ┆ 0   ┆ 1,9 ┆ 11  ┆ 15  ┆ 3   ┆ 875 ┆ 125 ┆ 29  ┆ 2   ┆ 710 ┆ 20, ┆ 199 ┆ Nin ┆ NIN ┆ 199 │
│ 8-1 ┆ 8-1 ┆ 8-1 ┆ 8-1 ┆     ┆     ┆ 72  ┆     ┆ 98  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 499 ┆ 6-0 ┆ ten ┆ TEN ┆ 8Q4 │
│ 1-1 ┆ 1-0 ┆ 1-1 ┆ 1-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6-2 ┆ do  ┆ DO6 ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 3   ┆     ┆ 4   ┆     │
│ 64  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   ┆ …   │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 57, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 255 ┆ 36  ┆ 8   ┆ 1   ┆ 8,2 ┆ 4,4 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 779 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 54  ┆ 30, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 672 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 26, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 3,2 ┆ 467 ┆ 107 ┆ 9   ┆ 3,7 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 481 ┆     ┆ 26  ┆     ┆     ┆     ┆ 71  ┆     ┆     ┆     ┆ 83  ┆ 553 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,32 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS4 ┆ 25  ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 4,3 ┆ 625 ┆ 144 ┆ 12  ┆ 3   ┆ 9,4 ┆ 201 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆ 91, ┆ 4-0 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 160 ┆ 2-2 ┆     ┆ ati ┆     │
│ 5_P ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on4 ┆     │
│ S4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 11, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 1,9 ┆ 274 ┆ 63  ┆ 6   ┆ 1,6 ┆ 7,3 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 588 ┆     ┆ 26  ┆     ┆     ┆     ┆ 21  ┆     ┆     ┆     ┆ 55  ┆ 98, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 379 ┆ 1-1 ┆     ┆ ati ┆     │
│ 5_P ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 755 ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 1,9 ┆ 274 ┆ 63  ┆ 6   ┆ 107 ┆ 693 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 23  ┆     ┆     ┆     ┆     ┆ ,36 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 5_X ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 63, ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 262 ┆ 37  ┆ 8   ┆ 1   ┆ 9,0 ┆ 4,4 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 313 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆ 93, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 985 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 2_N ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 28, ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 3,2 ┆ 468 ┆ 107 ┆ 9   ┆ 4,0 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │

## extract_week_reached_units

In [18]:
ex_df = g.extract_week_reached_units(base_df, threshold_units=5_000_000)
ex_df.select([pl.col('hw'), pl.col('delta_week')])
ex_df.sort('delta_week').select([pl.col('hw'), pl.col('delta_week')])

┌──────┬────────────┐
│ hw   ┆ delta_week │
│ ---  ┆ ---        │
│ str  ┆ i32        │
╞══════╪════════════╡
│ 3DS  ┆ 51         │
│ GBA  ┆ 53         │
│ DS   ┆ 56         │
│ Wii  ┆ 59         │
│ PS2  ┆ 78         │
│ NSW  ┆ 78         │
│ PSP  ┆ 116        │
│ PS5  ┆ 164        │
│ PS3  ┆ 178        │
│ PS4  ┆ 180        │
│ Vita ┆ 248        │
│ GB   ┆ 589        │
└──────┴────────────┘

## extract_by_date

In [6]:
za_df = g.extract_by_date(base_df, target_date=datetime(2025,10,16), hw=["NS2", "PS5"])
za_df

┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ wee ┆ beg ┆ end ┆ rep ┆ per ┆ hw  ┆ uni ┆ adj ┆ yea ┆ mon ┆ mda ┆ wee ┆ del ┆ del ┆ del ┆ del ┆ avg ┆ sum ┆ lau ┆ mak ┆ ful ┆ qua │
│ kly ┆ in_ ┆ _da ┆ ort ┆ iod ┆ --- ┆ ts  ┆ ust ┆ r   ┆ th  ┆ y   ┆ k   ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ _un ┆ _un ┆ nch ┆ er_ ┆ l_n ┆ rte │
│ _id ┆ dat ┆ te  ┆ _da ┆ _da ┆ str ┆ --- ┆ _un ┆ --- ┆ --- ┆ --- ┆ --- ┆ day ┆ wee ┆ mon ┆ yea ┆ its ┆ its ┆ _da ┆ nam ┆ ame ┆ r   │
│ --- ┆ e   ┆ --- ┆ te  ┆ te  ┆     ┆ i64 ┆ its ┆ i16 ┆ i16 ┆ i16 ┆ i16 ┆ --- ┆ k   ┆ th  ┆ r   ┆ --- ┆ --- ┆ te  ┆ e   ┆ --- ┆ --- │
│ str ┆ --- ┆ dat ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ str ┆ str │
│     ┆ dat ┆ e   ┆ dat ┆ i16 ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ i16 ┆ i16 ┆     ┆     ┆ dat ┆ str ┆     ┆     │
│     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 201 ┆ 0   ┆ 2,0 ┆ 10  ┆ 19  ┆ 3   ┆ 136 ┆ 19  ┆ 4   ┆ 0   ┆ 28, ┆ 2,4 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆     ┆     ┆ ,68 ┆     ┆ 25  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 812 ┆ 02, ┆ 5-0 ┆ ten ┆ ten ┆ 5Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 587 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 9_N ┆ 3   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 12, ┆ 0   ┆ 2,0 ┆ 10  ┆ 19  ┆ 3   ┆ 1,8 ┆ 257 ┆ 59  ┆ 5   ┆ 1,7 ┆ 7,1 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 5-1 ┆ 5-1 ┆ 5-1 ┆ 5-1 ┆     ┆     ┆ 085 ┆     ┆ 25  ┆     ┆     ┆     ┆ 02  ┆     ┆     ┆     ┆ 26  ┆ 11, ┆ 0-1 ┆ Y   ┆ ySt ┆ 5Q4 │
│ 0-1 ┆ 0-1 ┆ 0-1 ┆ 0-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 164 ┆ 1-1 ┆     ┆ ati ┆     │
│ 9_P ┆ 3   ┆ 9   ┆ 9   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## extract_latest

In [7]:
latest_df = g.extract_latest(base_df, 4)
latest_df

┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ wee ┆ beg ┆ end ┆ rep ┆ per ┆ hw  ┆ uni ┆ adj ┆ yea ┆ mon ┆ mda ┆ wee ┆ del ┆ del ┆ del ┆ del ┆ avg ┆ sum ┆ lau ┆ mak ┆ ful ┆ qua │
│ kly ┆ in_ ┆ _da ┆ ort ┆ iod ┆ --- ┆ ts  ┆ ust ┆ r   ┆ th  ┆ y   ┆ k   ┆ ta_ ┆ ta_ ┆ ta_ ┆ ta_ ┆ _un ┆ _un ┆ nch ┆ er_ ┆ l_n ┆ rte │
│ _id ┆ dat ┆ te  ┆ _da ┆ _da ┆ str ┆ --- ┆ _un ┆ --- ┆ --- ┆ --- ┆ --- ┆ day ┆ wee ┆ mon ┆ yea ┆ its ┆ its ┆ _da ┆ nam ┆ ame ┆ r   │
│ --- ┆ e   ┆ --- ┆ te  ┆ te  ┆     ┆ i64 ┆ its ┆ i16 ┆ i16 ┆ i16 ┆ i16 ┆ --- ┆ k   ┆ th  ┆ r   ┆ --- ┆ --- ┆ te  ┆ e   ┆ --- ┆ --- │
│ str ┆ --- ┆ dat ┆ --- ┆ --- ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ --- ┆ --- ┆ i64 ┆ i64 ┆ --- ┆ --- ┆ str ┆ str │
│     ┆ dat ┆ e   ┆ dat ┆ i16 ┆     ┆     ┆ i64 ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ i16 ┆ i16 ┆     ┆     ┆ dat ┆ str ┆     ┆     │
│     ┆ e   ┆     ┆ e   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ e   ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 57, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 255 ┆ 36  ┆ 8   ┆ 1   ┆ 8,2 ┆ 4,4 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 779 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 54  ┆ 30, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 672 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 26, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 3,2 ┆ 467 ┆ 107 ┆ 9   ┆ 3,7 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 481 ┆     ┆ 26  ┆     ┆     ┆     ┆ 71  ┆     ┆     ┆     ┆ 83  ┆ 553 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,32 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 5_N ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 1   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 11, ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 1,9 ┆ 274 ┆ 63  ┆ 6   ┆ 1,6 ┆ 7,3 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 588 ┆     ┆ 26  ┆     ┆     ┆     ┆ 21  ┆     ┆     ┆     ┆ 55  ┆ 98, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 379 ┆ 1-1 ┆     ┆ ati ┆     │
│ 5_P ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 755 ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 1,9 ┆ 274 ┆ 63  ┆ 6   ┆ 107 ┆ 693 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 23  ┆     ┆     ┆     ┆     ┆ ,36 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 4   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 5_X ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS4 ┆ 25  ┆ 0   ┆ 2,0 ┆ 2   ┆ 15  ┆ 3   ┆ 4,3 ┆ 625 ┆ 144 ┆ 12  ┆ 3   ┆ 9,4 ┆ 201 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 76  ┆     ┆     ┆     ┆     ┆ 91, ┆ 4-0 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-1 ┆ 2-0 ┆ 2-1 ┆ 2-1 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 160 ┆ 2-2 ┆     ┆ ati ┆     │
│ 5_P ┆ 9   ┆ 5   ┆ 5   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on4 ┆     │
│ S4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 63, ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 262 ┆ 37  ┆ 8   ┆ 1   ┆ 9,0 ┆ 4,4 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 313 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44  ┆ 93, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 985 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 2_N ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 28, ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 3,2 ┆ 468 ┆ 107 ┆ 9   ┆ 4,0 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 426 ┆     ┆ 26  ┆     ┆     ┆     ┆ 78  ┆     ┆     ┆     ┆ 60  ┆ 581 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,74 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 2_N ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 10, ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 1,9 ┆ 275 ┆ 63  ┆ 6   ┆ 1,4 ┆ 7,4 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 343 ┆     ┆ 26  ┆     ┆     ┆     ┆ 28  ┆     ┆     ┆     ┆ 77  ┆ 08, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 722 ┆ 1-1 ┆     ┆ ati ┆     │
│ 2_P ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 1,1 ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 1,9 ┆ 275 ┆ 63  ┆ 6   ┆ 169 ┆ 694 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 88  ┆     ┆ 26  ┆     ┆     ┆     ┆ 30  ┆     ┆     ┆     ┆     ┆ ,55 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 2_X ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS4 ┆ 37  ┆ 0   ┆ 2,0 ┆ 2   ┆ 22  ┆ 4   ┆ 4,3 ┆ 626 ┆ 144 ┆ 12  ┆ 5   ┆ 9,4 ┆ 201 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 83  ┆     ┆     ┆     ┆     ┆ 91, ┆ 4-0 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 2-2 ┆ 2-1 ┆ 2-2 ┆ 2-2 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 197 ┆ 2-2 ┆     ┆ ati ┆     │
│ 2_P ┆ 6   ┆ 2   ┆ 2   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on4 ┆     │
│ S4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 85, ┆ 0   ┆ 2,0 ┆ 3   ┆ 1   ┆ 1   ┆ 269 ┆ 38  ┆ 9   ┆ 1   ┆ 12, ┆ 4,5 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 830 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 261 ┆ 79, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 3-0 ┆ 2-2 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 815 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 1_N ┆ 3   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 22, ┆ 0   ┆ 2,0 ┆ 3   ┆ 1   ┆ 1   ┆ 3,2 ┆ 469 ┆ 108 ┆ 9   ┆ 3,1 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 260 ┆     ┆ 26  ┆     ┆     ┆     ┆ 85  ┆     ┆     ┆     ┆ 80  ┆ 604 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 3-0 ┆ 2-2 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,00 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 1_N ┆ 3   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 15, ┆ 0   ┆ 2,0 ┆ 3   ┆ 1   ┆ 1   ┆ 1,9 ┆ 276 ┆ 64  ┆ 6   ┆ 2,1 ┆ 7,4 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 048 ┆     ┆ 26  ┆     ┆     ┆     ┆ 35  ┆     ┆     ┆     ┆ 49  ┆ 23, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 3-0 ┆ 2-2 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 770 ┆ 1-1 ┆     ┆ ati ┆     │
│ 1_P ┆ 3   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 648 ┆ 0   ┆ 2,0 ┆ 3   ┆ 1   ┆ 1   ┆ 1,9 ┆ 276 ┆ 64  ┆ 6   ┆ 92  ┆ 695 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 37  ┆     ┆     ┆     ┆     ┆ ,20 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q1 │
│ 3-0 ┆ 2-2 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 1_X ┆ 3   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS4 ┆ 35  ┆ 0   ┆ 2,0 ┆ 3   ┆ 1   ┆ 1   ┆ 4,3 ┆ 627 ┆ 145 ┆ 12  ┆ 5   ┆ 9,4 ┆ 201 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 90  ┆     ┆     ┆     ┆     ┆ 91, ┆ 4-0 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 3-0 ┆ 2-2 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 232 ┆ 2-2 ┆     ┆ ati ┆     │
│ 1_P ┆ 3   ┆ 1   ┆ 1   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on4 ┆     │
│ S4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NS2 ┆ 127 ┆ 0   ┆ 2,0 ┆ 3   ┆ 8   ┆ 2   ┆ 276 ┆ 39  ┆ 9   ┆ 1   ┆ 18, ┆ 4,7 ┆ 202 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ ,50 ┆     ┆ 26  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 215 ┆ 07, ┆ 5-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 3-0 ┆ 3-0 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 323 ┆ 6-0 ┆ do  ┆ do  ┆     │
│ 8_N ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 5   ┆     ┆ Swi ┆     │
│ S2  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ NSW ┆ 23, ┆ 0   ┆ 2,0 ┆ 3   ┆ 8   ┆ 2   ┆ 3,2 ┆ 470 ┆ 108 ┆ 9   ┆ 3,3 ┆ 36, ┆ 201 ┆ Nin ┆ Nin ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 770 ┆     ┆ 26  ┆     ┆     ┆     ┆ 92  ┆     ┆     ┆     ┆ 95  ┆ 627 ┆ 7-0 ┆ ten ┆ ten ┆ 6Q1 │
│ 3-0 ┆ 3-0 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ,77 ┆ 3-0 ┆ do  ┆ do  ┆     │
│ 8_N ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 7   ┆ 3   ┆     ┆ Swi ┆     │
│ SW  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tch ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS5 ┆ 16, ┆ 0   ┆ 2,0 ┆ 3   ┆ 8   ┆ 2   ┆ 1,9 ┆ 277 ┆ 64  ┆ 6   ┆ 2,4 ┆ 7,4 ┆ 202 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆ 819 ┆     ┆ 26  ┆     ┆     ┆     ┆ 42  ┆     ┆     ┆     ┆ 02  ┆ 40, ┆ 0-1 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 3-0 ┆ 3-0 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 589 ┆ 1-1 ┆     ┆ ati ┆     │
│ 8_P ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on5 ┆     │
│ S5  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ XSX ┆ 486 ┆ 0   ┆ 2,0 ┆ 3   ┆ 8   ┆ 2   ┆ 1,9 ┆ 277 ┆ 64  ┆ 6   ┆ 69  ┆ 695 ┆ 202 ┆ Mic ┆ Xbo ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 44  ┆     ┆     ┆     ┆     ┆ ,68 ┆ 0-1 ┆ ros ┆ x   ┆ 6Q1 │
│ 3-0 ┆ 3-0 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 6   ┆ 1-1 ┆ oft ┆ Ser ┆     │
│ 8_X ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 0   ┆     ┆ ies ┆     │
│ SX  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ X|S ┆     │
│ 202 ┆ 202 ┆ 202 ┆ 202 ┆ 7   ┆ PS4 ┆ 29  ┆ 0   ┆ 2,0 ┆ 3   ┆ 8   ┆ 2   ┆ 4,3 ┆ 628 ┆ 145 ┆ 12  ┆ 4   ┆ 9,4 ┆ 201 ┆ SON ┆ Pla ┆ 202 │
│ 6-0 ┆ 6-0 ┆ 6-0 ┆ 6-0 ┆     ┆     ┆     ┆     ┆ 26  ┆     ┆     ┆     ┆ 97  ┆     ┆     ┆     ┆     ┆ 91, ┆ 4-0 ┆ Y   ┆ ySt ┆ 6Q1 │
│ 3-0 ┆ 3-0 ┆ 3-0 ┆ 3-0 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 261 ┆ 2-2 ┆     ┆ ati ┆     │
│ 8_P ┆ 2   ┆ 8   ┆ 8   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 2   ┆     ┆ on4 ┆     │
│ S4  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
└─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┴─────┘

## current_report_date

In [8]:
current_date = g.current_report_date(base_df)
current_date

datetime.date(2026, 3, 8)

## get_hw

In [9]:
hw_list = g.get_hw(latest_df)
hw_list

['XSX', 'PS5', 'PS4', 'NS2', 'NSW']

## get_active_hw

In [10]:
hw_list = g.get_active_hw()
hw_list

['XSX', 'NSW', 'PS5', 'PS4', 'NS2']

## weekly_sales

In [11]:
weekly_df = g.weekly_sales(base_df, begin=datetime(2025,1,1))
weekly_df

┌─────────────┬─────┬──────────────┬───────────┐
│ report_date ┆ hw  ┆ weekly_units ┆ sum_units │
│ ---         ┆ --- ┆ ---          ┆ ---       │
│ date        ┆ str ┆ i64          ┆ i64       │
╞═════════════╪═════╪══════════════╪═══════════╡
│ 2025-01-05  ┆ NSW ┆ 109,729      ┆ 109,729   │
│ 2025-01-05  ┆ PS5 ┆ 46,680       ┆ 46,680    │
│ 2025-01-05  ┆ XSX ┆ 1,113        ┆ 1,113     │
│ 2025-01-05  ┆ PS4 ┆ 35           ┆ 35        │
│ 2025-01-12  ┆ NSW ┆ 57,831       ┆ 167,560   │
│ 2025-01-12  ┆ PS5 ┆ 11,828       ┆ 58,508    │
│ 2025-01-12  ┆ XSX ┆ 876          ┆ 1,989     │
│ 2025-01-12  ┆ PS4 ┆ 31           ┆ 66        │
│ 2025-01-19  ┆ NSW ┆ 47,560       ┆ 215,120   │
│ 2025-01-19  ┆ PS5 ┆ 10,738       ┆ 69,246    │
│ 2025-01-19  ┆ XSX ┆ 785          ┆ 2,774     │
│ 2025-01-19  ┆ PS4 ┆ 29           ┆ 95        │
│ 2025-01-26  ┆ NSW ┆ 45,327       ┆ 260,447   │
│ 2025-01-26  ┆ PS5 ┆ 12,341       ┆ 81,587    │
│ 2025-01-26  ┆ XSX ┆ 1,087        ┆ 3,861     │
│ 2025-01-26  ┆ PS4 ┆ 31           ┆ 126       │
│ 2025-02-02  ┆ NSW ┆ 44,341       ┆ 304,788   │
│ 2025-02-02  ┆ PS5 ┆ 12,873       ┆ 94,460    │
│ 2025-02-02  ┆ XSX ┆ 3,070        ┆ 6,931     │
│ 2025-02-02  ┆ PS4 ┆ 19           ┆ 145       │
│ …           ┆ …   ┆ …            ┆ …         │
│ 2026-02-15  ┆ NS2 ┆ 57,779       ┆ 4,430,672 │
│ 2026-02-15  ┆ NSW ┆ 26,481       ┆ 1,657,544 │
│ 2026-02-15  ┆ PS5 ┆ 11,588       ┆ 979,373   │
│ 2026-02-15  ┆ XSX ┆ 755          ┆ 35,036    │
│ 2026-02-15  ┆ PS4 ┆ 25           ┆ 1,200     │
│ 2026-02-22  ┆ NS2 ┆ 63,313       ┆ 4,493,985 │
│ 2026-02-22  ┆ NSW ┆ 28,426       ┆ 1,685,970 │
│ 2026-02-22  ┆ PS5 ┆ 10,343       ┆ 989,716   │
│ 2026-02-22  ┆ XSX ┆ 1,188        ┆ 36,224    │
│ 2026-02-22  ┆ PS4 ┆ 37           ┆ 1,237     │
│ 2026-03-01  ┆ NS2 ┆ 85,830       ┆ 4,579,815 │
│ 2026-03-01  ┆ NSW ┆ 22,260       ┆ 1,708,230 │
│ 2026-03-01  ┆ PS5 ┆ 15,048       ┆ 1,004,764 │
│ 2026-03-01  ┆ XSX ┆ 648          ┆ 36,872    │
│ 2026-03-01  ┆ PS4 ┆ 35           ┆ 1,272     │
│ 2026-03-08  ┆ NS2 ┆ 127,508      ┆ 4,707,323 │
│ 2026-03-08  ┆ NSW ┆ 23,770       ┆ 1,732,000 │
│ 2026-03-08  ┆ PS5 ┆ 16,819       ┆ 1,021,583 │
│ 2026-03-08  ┆ XSX ┆ 486          ┆ 37,358    │
│ 2026-03-08  ┆ PS4 ┆ 29           ┆ 1,301     │
└─────────────┴─────┴──────────────┴───────────┘

## monthly_sales

In [12]:
monthly_df = g.monthly_sales(base_df, begin=datetime(2024,1,1))
monthly_df

┌───────┬───────┬─────┬───────────────┬───────────┐
│ year  ┆ month ┆ hw  ┆ monthly_units ┆ sum_units │
│ ---   ┆ ---   ┆ --- ┆ ---           ┆ ---       │
│ i16   ┆ i16   ┆ str ┆ i64           ┆ i64       │
╞═══════╪═══════╪═════╪═══════════════╪═══════════╡
│ 2,024 ┆ 1     ┆ NSW ┆ 241,282       ┆ 241,282   │
│ 2,024 ┆ 1     ┆ PS5 ┆ 185,480       ┆ 185,480   │
│ 2,024 ┆ 1     ┆ XSX ┆ 8,281         ┆ 8,281     │
│ 2,024 ┆ 1     ┆ PS4 ┆ 2,574         ┆ 2,574     │
│ 2,024 ┆ 1     ┆ 3DS ┆ 57            ┆ 57        │
│ 2,024 ┆ 2     ┆ NSW ┆ 190,786       ┆ 432,068   │
│ 2,024 ┆ 2     ┆ PS5 ┆ 146,945       ┆ 332,425   │
│ 2,024 ┆ 2     ┆ XSX ┆ 11,030        ┆ 19,311    │
│ 2,024 ┆ 2     ┆ PS4 ┆ 2,374         ┆ 4,948     │
│ 2,024 ┆ 2     ┆ 3DS ┆ 51            ┆ 108       │
│ 2,024 ┆ 3     ┆ NSW ┆ 289,673       ┆ 721,741   │
│ 2,024 ┆ 3     ┆ PS5 ┆ 162,281       ┆ 494,706   │
│ 2,024 ┆ 3     ┆ XSX ┆ 10,329        ┆ 29,640    │
│ 2,024 ┆ 3     ┆ PS4 ┆ 5,055         ┆ 10,003    │
│ 2,024 ┆ 3     ┆ 3DS ┆ 54            ┆ 162       │
│ 2,024 ┆ 4     ┆ NSW ┆ 257,515       ┆ 979,256   │
│ 2,024 ┆ 4     ┆ PS5 ┆ 91,981        ┆ 586,687   │
│ 2,024 ┆ 4     ┆ XSX ┆ 10,185        ┆ 39,825    │
│ 2,024 ┆ 4     ┆ PS4 ┆ 341           ┆ 10,344    │
│ 2,024 ┆ 5     ┆ NSW ┆ 185,821       ┆ 1,165,077 │
│ …     ┆ …     ┆ …   ┆ …             ┆ …         │
│ 2,025 ┆ 12    ┆ NS2 ┆ 815,632       ┆ 3,784,067 │
│ 2,025 ┆ 12    ┆ NSW ┆ 153,619       ┆ 4,629,487 │
│ 2,025 ┆ 12    ┆ PS5 ┆ 82,691        ┆ 2,333,353 │
│ 2,025 ┆ 12    ┆ XSX ┆ 895           ┆ 149,447   │
│ 2,025 ┆ 12    ┆ PS4 ┆ 60            ┆ 14,815    │
│ 2,026 ┆ 1     ┆ NS2 ┆ 453,433       ┆ 4,237,500 │
│ 2,026 ┆ 1     ┆ NSW ┆ 91,109        ┆ 4,720,596 │
│ 2,026 ┆ 1     ┆ PS5 ┆ 66,502        ┆ 2,399,855 │
│ 2,026 ┆ 1     ┆ XSX ┆ 1,277         ┆ 150,724   │
│ 2,026 ┆ 1     ┆ PS4 ┆ 53            ┆ 14,868    │
│ 2,026 ┆ 2     ┆ NS2 ┆ 256,485       ┆ 4,493,985 │
│ 2,026 ┆ 2     ┆ NSW ┆ 74,477        ┆ 4,795,073 │
│ 2,026 ┆ 2     ┆ PS5 ┆ 44,010        ┆ 2,443,865 │
│ 2,026 ┆ 2     ┆ XSX ┆ 3,721         ┆ 154,445   │
│ 2,026 ┆ 2     ┆ PS4 ┆ 97            ┆ 14,965    │
│ 2,026 ┆ 3     ┆ NS2 ┆ 213,338       ┆ 4,707,323 │
│ 2,026 ┆ 3     ┆ NSW ┆ 46,030        ┆ 4,841,103 │
│ 2,026 ┆ 3     ┆ PS5 ┆ 31,867        ┆ 2,475,732 │
│ 2,026 ┆ 3     ┆ XSX ┆ 1,134         ┆ 155,579   │
│ 2,026 ┆ 3     ┆ PS4 ┆ 64            ┆ 15,029    │
└───────┴───────┴─────┴───────────────┴───────────┘

## quarterly_sales

In [13]:
quarterly_sales_df =  g.quarterly_sales(base_df, begin=datetime(2020,1,1), end=datetime(2022,12,31))
quarterly_sales_df

┌─────────┬───────┬─────────────────┬───────┬───────┬────────────┐
│ quarter ┆ hw    ┆ quarterly_units ┆ year  ┆ q_num ┆ sum_units  │
│ ---     ┆ ---   ┆ ---             ┆ ---   ┆ ---   ┆ ---        │
│ str     ┆ str   ┆ i64             ┆ i64   ┆ i64   ┆ i64        │
╞═════════╪═══════╪═════════════════╪═══════╪═══════╪════════════╡
│ 2020Q1  ┆ NSW   ┆ 1,700,352       ┆ 2,020 ┆ 1     ┆ 1,700,352  │
│ 2020Q1  ┆ PS4   ┆ 170,086         ┆ 2,020 ┆ 1     ┆ 170,086    │
│ 2020Q1  ┆ 3DS   ┆ 15,170          ┆ 2,020 ┆ 1     ┆ 15,170     │
│ 2020Q1  ┆ XBOne ┆ 1,404           ┆ 2,020 ┆ 1     ┆ 1,404      │
│ 2020Q2  ┆ NSW   ┆ 966,530         ┆ 2,020 ┆ 2     ┆ 2,666,882  │
│ 2020Q2  ┆ PS4   ┆ 265,726         ┆ 2,020 ┆ 2     ┆ 435,812    │
│ 2020Q2  ┆ 3DS   ┆ 18,170          ┆ 2,020 ┆ 2     ┆ 33,340     │
│ 2020Q2  ┆ XBOne ┆ 1,283           ┆ 2,020 ┆ 2     ┆ 2,687      │
│ 2020Q3  ┆ NSW   ┆ 1,287,203       ┆ 2,020 ┆ 3     ┆ 3,954,085  │
│ 2020Q3  ┆ PS4   ┆ 38,029          ┆ 2,020 ┆ 3     ┆ 473,841    │
│ 2020Q3  ┆ 3DS   ┆ 19,516          ┆ 2,020 ┆ 3     ┆ 52,856     │
│ 2020Q3  ┆ XBOne ┆ 461             ┆ 2,020 ┆ 3     ┆ 3,148      │
│ 2020Q4  ┆ NSW   ┆ 2,002,858       ┆ 2,020 ┆ 4     ┆ 5,956,943  │
│ 2020Q4  ┆ PS5   ┆ 255,150         ┆ 2,020 ┆ 4     ┆ 255,150    │
│ 2020Q4  ┆ PS4   ┆ 68,806          ┆ 2,020 ┆ 4     ┆ 542,647    │
│ 2020Q4  ┆ XSX   ┆ 31,424          ┆ 2,020 ┆ 4     ┆ 31,424     │
│ 2020Q4  ┆ 3DS   ┆ 9,905           ┆ 2,020 ┆ 4     ┆ 62,761     │
│ 2020Q4  ┆ XBOne ┆ 437             ┆ 2,020 ┆ 4     ┆ 3,585      │
│ 2021Q1  ┆ NSW   ┆ 1,744,974       ┆ 2,021 ┆ 1     ┆ 7,701,917  │
│ 2021Q1  ┆ PS5   ┆ 325,061         ┆ 2,021 ┆ 1     ┆ 580,211    │
│ …       ┆ …     ┆ …               ┆ …     ┆ …     ┆ …          │
│ 2022Q1  ┆ NSW   ┆ 1,357,610       ┆ 2,022 ┆ 1     ┆ 12,893,680 │
│ 2022Q1  ┆ PS5   ┆ 274,182         ┆ 2,022 ┆ 1     ┆ 1,497,517  │
│ 2022Q1  ┆ XSX   ┆ 35,632          ┆ 2,022 ┆ 1     ┆ 164,290    │
│ 2022Q1  ┆ 3DS   ┆ 5,297           ┆ 2,022 ┆ 1     ┆ 96,598     │
│ 2022Q1  ┆ PS4   ┆ 171             ┆ 2,022 ┆ 1     ┆ 646,872    │
│ 2022Q2  ┆ NSW   ┆ 840,247         ┆ 2,022 ┆ 2     ┆ 13,733,927 │
│ 2022Q2  ┆ PS5   ┆ 205,667         ┆ 2,022 ┆ 2     ┆ 1,703,184  │
│ 2022Q2  ┆ XSX   ┆ 83,684          ┆ 2,022 ┆ 2     ┆ 247,974    │
│ 2022Q2  ┆ 3DS   ┆ 2,855           ┆ 2,022 ┆ 2     ┆ 99,453     │
│ 2022Q2  ┆ PS4   ┆ 326             ┆ 2,022 ┆ 2     ┆ 647,198    │
│ 2022Q3  ┆ NSW   ┆ 1,175,735       ┆ 2,022 ┆ 3     ┆ 14,909,662 │
│ 2022Q3  ┆ PS5   ┆ 252,019         ┆ 2,022 ┆ 3     ┆ 1,955,203  │
│ 2022Q3  ┆ XSX   ┆ 102,453         ┆ 2,022 ┆ 3     ┆ 350,427    │
│ 2022Q3  ┆ 3DS   ┆ 1,551           ┆ 2,022 ┆ 3     ┆ 101,004    │
│ 2022Q3  ┆ PS4   ┆ 164             ┆ 2,022 ┆ 3     ┆ 647,362    │
│ 2022Q4  ┆ NSW   ┆ 1,430,954       ┆ 2,022 ┆ 4     ┆ 16,340,616 │
│ 2022Q4  ┆ PS5   ┆ 422,186         ┆ 2,022 ┆ 4     ┆ 2,377,389  │
│ 2022Q4  ┆ XSX   ┆ 47,968          ┆ 2,022 ┆ 4     ┆ 398,395    │
│ 2022Q4  ┆ PS4   ┆ 22,162          ┆ 2,022 ┆ 4     ┆ 669,524    │
│ 2022Q4  ┆ 3DS   ┆ 961             ┆ 2,022 ┆ 4     ┆ 101,965    │
└─────────┴───────┴─────────────────┴───────┴───────┴────────────┘

## yearly_sales

In [14]:
yearly_df = g.yearly_sales(base_df, begin=datetime(2020,1,1), maker_mode=True)
yearly_df

┌───────┬────────────┬──────────────┬────────────┐
│ year  ┆ maker_name ┆ yearly_units ┆ sum_units  │
│ ---   ┆ ---        ┆ ---          ┆ ---        │
│ i16   ┆ str        ┆ i64          ┆ i64        │
╞═══════╪════════════╪══════════════╪════════════╡
│ 2,020 ┆ Nintendo   ┆ 6,019,704    ┆ 6,019,704  │
│ 2,020 ┆ SONY       ┆ 797,797      ┆ 797,797    │
│ 2,020 ┆ Microsoft  ┆ 35,009       ┆ 35,009     │
│ 2,021 ┆ Nintendo   ┆ 5,607,667    ┆ 11,627,371 │
│ 2,021 ┆ SONY       ┆ 1,072,239    ┆ 1,870,036  │
│ 2,021 ┆ Microsoft  ┆ 97,234       ┆ 132,243    │
│ 2,022 ┆ Nintendo   ┆ 4,815,210    ┆ 16,442,581 │
│ 2,022 ┆ SONY       ┆ 1,176,877    ┆ 3,046,913  │
│ 2,022 ┆ Microsoft  ┆ 269,737      ┆ 401,980    │
│ 2,023 ┆ Nintendo   ┆ 4,065,642    ┆ 20,508,223 │
│ 2,023 ┆ SONY       ┆ 2,660,760    ┆ 5,707,673  │
│ 2,023 ┆ Microsoft  ┆ 141,712      ┆ 543,692    │
│ 2,024 ┆ Nintendo   ┆ 3,109,265    ┆ 23,617,488 │
│ 2,024 ┆ SONY       ┆ 1,467,877    ┆ 7,175,550  │
│ 2,024 ┆ Microsoft  ┆ 118,221      ┆ 661,913    │
│ 2,025 ┆ Nintendo   ┆ 5,304,451    ┆ 28,921,939 │
│ 2,025 ┆ SONY       ┆ 880,291      ┆ 8,055,841  │
│ 2,025 ┆ Microsoft  ┆ 31,226       ┆ 693,139    │
│ 2,026 ┆ Nintendo   ┆ 1,134,872    ┆ 30,056,811 │
│ 2,026 ┆ SONY       ┆ 142,593      ┆ 8,198,434  │
│ 2,026 ┆ Microsoft  ┆ 6,132        ┆ 699,271    │
└───────┴────────────┴──────────────┴────────────┘

## yearly_maker_sales

In [15]:
mk_df = g.yearly_maker_sales(base_df, begin=datetime(2020,1,1))
mk_df

┌───────┬────────────┬──────────────┐
│ year  ┆ maker_name ┆ yearly_units │
│ ---   ┆ ---        ┆ ---          │
│ i16   ┆ str        ┆ i64          │
╞═══════╪════════════╪══════════════╡
│ 2,020 ┆ Nintendo   ┆ 6,019,704    │
│ 2,020 ┆ SONY       ┆ 797,797      │
│ 2,020 ┆ Microsoft  ┆ 35,009       │
│ 2,021 ┆ Nintendo   ┆ 5,607,667    │
│ 2,021 ┆ SONY       ┆ 1,072,239    │
│ 2,021 ┆ Microsoft  ┆ 97,234       │
│ 2,022 ┆ Nintendo   ┆ 4,815,210    │
│ 2,022 ┆ SONY       ┆ 1,176,877    │
│ 2,022 ┆ Microsoft  ┆ 269,737      │
│ 2,023 ┆ Nintendo   ┆ 4,065,642    │
│ 2,023 ┆ SONY       ┆ 2,660,760    │
│ 2,023 ┆ Microsoft  ┆ 141,712      │
│ 2,024 ┆ Nintendo   ┆ 3,109,265    │
│ 2,024 ┆ SONY       ┆ 1,467,877    │
│ 2,024 ┆ Microsoft  ┆ 118,221      │
│ 2,025 ┆ Nintendo   ┆ 5,304,451    │
│ 2,025 ┆ SONY       ┆ 880,291      │
│ 2,025 ┆ Microsoft  ┆ 31,226       │
│ 2,026 ┆ Nintendo   ┆ 1,134,872    │
│ 2,026 ┆ SONY       ┆ 142,593      │
│ 2,026 ┆ Microsoft  ┆ 6,132        │
└───────┴────────────┴──────────────┘

## delta_yearly_sales

In [16]:
dys_df = g.delta_yearly_sales(base_df)
dys_df

┌────────────┬───────┬──────────────┬────────────┐
│ delta_year ┆ hw    ┆ yearly_units ┆ sum_units  │
│ ---        ┆ ---   ┆ ---          ┆ ---        │
│ i16        ┆ str   ┆ i64          ┆ i64        │
╞════════════╪═══════╪══════════════╪════════════╡
│ 0          ┆ GBA   ┆ 4,245,686    ┆ 4,245,686  │
│ 0          ┆ 3DS   ┆ 4,132,038    ┆ 4,132,038  │
│ 0          ┆ NS2   ┆ 3,784,067    ┆ 3,784,067  │
│ 0          ┆ NSW   ┆ 3,407,158    ┆ 3,407,158  │
│ 0          ┆ PS2   ┆ 3,100,795    ┆ 3,100,795  │
│ 0          ┆ PKS   ┆ 2,723,757    ┆ 2,723,757  │
│ 0          ┆ DS    ┆ 1,056,428    ┆ 1,056,428  │
│ 0          ┆ Wii   ┆ 989,118      ┆ 989,118    │
│ 0          ┆ GC    ┆ 929,832      ┆ 929,832    │
│ 0          ┆ PS4   ┆ 925,570      ┆ 925,570    │
│ 0          ┆ WS    ┆ 684,517      ┆ 684,517    │
│ 0          ┆ WiiU  ┆ 635,290      ┆ 635,290    │
│ 0          ┆ PS3   ┆ 466,716      ┆ 466,716    │
│ 0          ┆ Vita  ┆ 402,794      ┆ 402,794    │
│ 0          ┆ PSP   ┆ 349,283      ┆ 349,283    │
│ 0          ┆ Xbox  ┆ 329,584      ┆ 329,584    │
│ 0          ┆ DC    ┆ 270,095      ┆ 270,095    │
│ 0          ┆ PS5   ┆ 255,150      ┆ 255,150    │
│ 0          ┆ XB360 ┆ 84,490       ┆ 84,490     │
│ 0          ┆ XBOne ┆ 45,958       ┆ 45,958     │
│ …          ┆ …     ┆ …            ┆ …          │
│ 9          ┆ PS    ┆ 60,418       ┆ 3,579,817  │
│ 9          ┆ XB360 ┆ 7,381        ┆ 1,602,537  │
│ 10         ┆ GB    ┆ 2,606,884    ┆ 3,665,748  │
│ 10         ┆ PS2   ┆ 89,573       ┆ 21,148,772 │
│ 10         ┆ PSP   ┆ 83,891       ┆ 19,458,755 │
│ 10         ┆ 3DS   ┆ 28,540       ┆ 24,374,435 │
│ 10         ┆ PS4   ┆ 13,728       ┆ 9,489,960  │
│ 10         ┆ PS    ┆ 984          ┆ 3,580,801  │
│ 11         ┆ GB    ┆ 2,077,410    ┆ 5,743,158  │
│ 11         ┆ PS2   ┆ 56,235       ┆ 21,205,007 │
│ 11         ┆ 3DS   ┆ 10,664       ┆ 24,385,099 │
│ 11         ┆ PS4   ┆ 1,087        ┆ 9,491,047  │
│ 12         ┆ GB    ┆ 528,362      ┆ 6,271,520  │
│ 12         ┆ PS2   ┆ 26,201       ┆ 21,231,208 │
│ 12         ┆ 3DS   ┆ 3,033        ┆ 24,388,132 │
│ 12         ┆ PS4   ┆ 214          ┆ 9,491,261  │
│ 13         ┆ GB    ┆ 109,226      ┆ 6,380,746  │
│ 13         ┆ PS2   ┆ 4,689        ┆ 21,235,897 │
│ 13         ┆ 3DS   ┆ 162          ┆ 24,388,294 │
│ 14         ┆ GB    ┆ 8,948        ┆ 6,389,694  │
└────────────┴───────┴──────────────┴────────────┘